Document: keepassxc
Title: Debian keepassxc Manual
Author: <insert document author here>
Abstract: This manual describes what keepassxc is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/keepassxc/keepassxc.sgml.gz

Format: postscript
Files: /usr/share/doc/keepassxc/keepassxc.ps.gz

Format: text
Files: /usr/share/doc/keepassxc/keepassxc.text.gz

Format: HTML
Index: /usr/share/doc/keepassxc/html/index.html
Files: /usr/share/doc/keepassxc/html/*.html
